version: '3'
services:
  web:
    image: nginx:latest
    container_name: bitframex
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  app:
    container_name: bitframephp
    build: .
    volumes:
      - ./www:/var/www/html
