version: '3.5'

volumes:
  vendor:

services:
  nginx:
    image: nginx:latest
    container_name: bitframe_ngx
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  app:
    container_name: bitframe_php
    build: .
    volumes:
      - ./www:/var/www/html
      - vendor:/var/www/html/vendor
